
[project]
license = "LGPL-3"

[metadata]
name = pyknic-todo
version = attr: pyknic_todo.version.__version__
description = Simple CLI todo list utility with JSON storage and recurrence support
long_description = file: README.md
long_description_content_type = text/markdown
author = Ildar Gafurov
author_email = dev@binblob.com
maintainer = Ildar Gafurov
maintainer_email = dev@binblob.com

license = LGPL-3
license_files =
  LICENSE
  AUTHORS

classifiers =
    Development Status :: 2 - Pre-Alpha
    Intended Audience :: Developers
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Environment :: Console

[options]
packages = find:
python_requires = >=3.11
install_requires =
    pydantic
    pydantic-settings
    pyknic
    python-dateutil

[options.packages.find]
exclude =
    tests*
    data*

[options.extras_require]
all =
    twine

    flake8
	mypy
	pytest
    pytest-cov
    pytest-html

dev =
	twine

test =
    flake8
    mypy
    pytest
    pytest-cov
    pytest-html

[options.entry_points]
console_scripts =
    pyknic-todo = pyknic_todo.cli:main

pyknic.plugins =
   main_plugin = pyknic_todo.bellboy:init_plugin

[tool:pytest]
python_files = tests/pytest/*.py
addopts = -v
  --html=docs/pytest/index.html
  --capture=sys
  --cov pyknic_todo
  --cov-report html:docs/pytest-coverage
  --cov-report xml:docs/pytest-coverage.xml
  --cov-report lcov:docs/pytest-coverage.lcov

[flake8]
extend-ignore = E275
max-line-length = 120
jobs = 2

exclude = 
    .git,
    __pycache__,
    build,
    dist
    venv
    .venv
