
# input vars:
#   repo_uri -- a git repository URI (default: https://github.com/a1ezzz/pyknic-todo)
#   branch -- a name of a git branch this pipeline is running on
#   github-access-token -- a token for PR status updates
#   pull_request_id -- a number of PR
#   commit -- a commit a PR is related to
#   pull_request_branch_name -- if defined then it is a name of a source branch, that PR is related to
#   extra_branch -- the same as pull_request_branch_name (or the branch)
#   python_version -- a version of CPython that is used within the code
#   tg_bot_token -- access token to Telegram bot
#   tg_chat -- target chat id to notify

# TODO: get rid off build-metadata-resource

resource_types:

  - name: build-metadata
    type: docker-image
    source:
      repository: mastertinner/build-metadata-resource

resources:

  - name: code
    type: git
    icon: github
    source:
      uri: ((repo_uri))
      branch: ((branch))

  - name: extra-branch
    type: git
    icon: github
    source:
      uri: ((repo_uri))
      branch: ((extra_branch))

  - name: pr-code
    type: git
    icon: github
    source:
      uri: ((repo_uri))
      branch: ((pull_request_branch_name))

  - name: metadata
    type: build-metadata

jobs:
  - name: pyknic-test-job-py-((python_version))
    build_log_retention:
      builds: 3
    plan:

      - get: code
        trigger: true

      - get: extra-branch
        trigger: true

      - get: pr-code

      - get: metadata

      - load_var: metadata_build_id
        file: metadata/build-id
        format: trim

      - task: run_tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: a1ezzz/pyknic-concourse-base-image-test
              tag: py-alpine-((python_version))
          inputs:
            - name: code
            - name: metadata
          outputs:
            - name: code
            - name: sandbox
              path: /sandbox
          params:
            SANDBOX_DIR: "/sandbox"
            PYTHON_VERSION: ((python_version))
            BUILD_URL: "https://concourse-ci.binblob.com/builds/((.:metadata_build_id))"
            BUILD_BRANCH: ((branch))
            TG_BOT_TOKEN: ((tg_bot_token))
            TG_CHAT_ID: ((tg_chat))
            TG_API_HOST: ((tg_api_host))
            GITHUB_PULL_REQUEST_ID: ((pull_request_id))
            GITHUB_ACCESS_TOKEN: ((github-access-token))
          run:
            dir: code
            path: /bin/bash
            args:
              - -ecx
              - |

                CODE_DIR="$(pwd)" \
                BUILD_COMMIT="$(git rev-parse $( [[ -n "((pull_request_id))" ]] && echo "((pull_request_branch_name))" || echo "HEAD" ))" \
                /scripts/run-tests.sh

        on_failure:
          task: set_status_as_failed
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: a1ezzz/pyknic-concourse-base-image-test
                tag: py-alpine-((python_version))
            inputs:
              - name: sandbox
                path: /sandbox
            params:
              SANDBOX_DIR: "/sandbox"
              PYTHON_VERSION: ((python_version))
              BUILD_URL: "https://concourse-ci.binblob.com/builds/((.:metadata_build_id))"
              TG_BOT_TOKEN: ((tg_bot_token))
              TG_CHAT_ID: ((tg_chat))
              TG_API_HOST: ((tg_api_host))
              GITHUB_PULL_REQUEST_ID: ((pull_request_id))
              GITHUB_ACCESS_TOKEN: ((github-access-token))
            run:
              path: /bin/bash
              args:
                - -ecx
                - |

                  if [[ ! -f /sandbox/error.feedback ]]; then
                    echo "Unknown error spotted!"

                    BUILD_COMMIT="$(git rev-parse $( [[ -n "((pull_request_id))" ]] && echo "((pull_request_branch_name))" || echo "HEAD" ))" \
                    /scripts/reset-feedback.sh

                    if [[ -n "${TG_BOT_TOKEN:-}" && -n "${TG_CHAT_ID:-}" ]]; then

                      curl \
                        -X POST \
                        "https://${TG_API_HOST}/bot${TG_BOT_TOKEN}/sendMessage" \
                        -d chat_id="${TG_CHAT_ID}" \
                        -d text="Unkown error spotted!"

                    fi

                  fi
